
version: 0.2
port: 8000

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - npm install
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION )
      - REPOSITORY_URI=368355641188.dkr.ecr.ap-southeast-2.amazonaws.com/us4-naba-docker
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:

      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 368355641188.dkr.ecr.ap-southeast-2.amazonaws.com
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"us4-naba-project","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json