version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ap-southeast-2 --no-include-email)
      - REPOSITORY_URI=368355641188.dkr.ecr.ap-southeast-2.amazonaws.com/us4-naba-docker
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t 368355641188.dkr.ecr.ap-southeast-2.amazonaws.com/us4-naba-docker:latest .
      - docker tag 368355641188.dkr.ecr.ap-southeast-2.amazonaws.com/us4-naba-docker:latest 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 368355641188.dkr.ecr.ap-southeast-2.amazonaws.com/us4-naba-docker:latest
      - echo Writing image definitions file...
      - printf '[{"name”:"us4-naba-td","imageUri":"%s"}]' 368355641188.dkr.ecr.ap-southeast-2.amazonaws.com/us4-naba-docker:$latest > imagedefinitions.json
      # - printf '[{"name":"<Your Container Name>","imageUri":"%s"}]'    $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json